import re

class TextCleaner:
    @staticmethod
    def clean_markdown_output(text: str) -> str:
        """
        Sanitizes and formats the raw markdown output generated by the LLM.
        Removes excessive whitespaces and redundant line breaks.
        """
        if not text:
            return ""
        
        # Replace 3 or more consecutive newline characters with exactly 2 newlines
        cleaned_text = re.sub(r'\n{3,}', '\n\n', text)
        
        # Strip leading and trailing whitespace
        return cleaned_text.strip()

# --- Testing the Module ---
if __name__ == "__main__":
    print("[INFO] Testing TextCleaner utility...")
    
    messy_text = "Here is the summary:\n\n\n\n\n- Point 1\n\n\n- Point 2"
    clean_text = TextCleaner.clean_markdown_output(messy_text)
    
    print("[SUCCESS] Original Length:", len(messy_text))
    print("[SUCCESS] Cleaned Length:", len(clean_text))